import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const contentDir = path.join(rootDir, "content");
const outputPath = path.join(contentDir, "research-digest.json");

const now = new Date();

const payload = {
  siteTitle: "Frontier Signals",
  tagline: "A small publishing system for recurring research and synthesized updates.",
  updatedAt: now.toISOString(),
  cadence: "weekly",
  summary:
    "This file is generated by the starter research script. Replace this script with your real agentic research workflow when you're ready.",
  topics: [
    {
      name: "AI infrastructure",
      signal: 78,
      change: "+6",
      note: "Cloud deployment patterns and infrastructure automation continue to converge."
    },
    {
      name: "Developer workflows",
      signal: 71,
      change: "+4",
      note: "Teams are codifying recurring research as scheduled jobs that publish directly from Git."
    },
    {
      name: "Web publishing",
      signal: 64,
      change: "+2",
      note: "Static-first publishing remains a strong default for editorial and analysis-heavy sites."
    }
  ],
  highlights: [
    "The homepage reads generated content directly from the repository.",
    "React is used only for selective interactivity inside an Astro site.",
    "Terraform is reserved for infrastructure, while CI handles builds."
  ]
};

await mkdir(contentDir, { recursive: true });
await writeFile(outputPath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");

console.log(`Wrote ${outputPath}`);
